pipeline {

    agent any

    environment {

        APP_PATH = "frontend\\education"

        DOCKER_IMAGE = "shivam312/education-app"

        DOCKER_TAG = "v${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Source Code') {

            steps {

                echo 'Cloning GitHub Repository...'

                checkout scm
            }
        }

        stage('Verify Project Files') {

            steps {

                echo 'Checking Files...'

                bat "dir"

                bat "dir ${APP_PATH}"
            }
        }

        stage('Build Docker Image') {

            steps {

                echo 'Building Docker Image...'

                bat """
                docker build ^
                -t ${DOCKER_IMAGE}:latest ^
                -t ${DOCKER_IMAGE}:${DOCKER_TAG} ^
                ./${APP_PATH}
                """
            }
        }

        stage('Docker Hub Login') {

            steps {

                echo 'Logging Into Docker Hub...'

                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-hub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {

                    bat """
                    echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                    """
                }
            }
        }

        stage('Push Docker Image') {

            steps {

                echo 'Pushing Docker Images...'

                bat "docker push ${DOCKER_IMAGE}:latest"

                bat "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
            }
        }
    }

    post {

        success {

            echo 'Pipeline Completed Successfully!'

            echo "${DOCKER_IMAGE}:${DOCKER_TAG}"
        }

        failure {

            echo 'Pipeline Failed'
        }

        always {

            echo 'Cleaning Workspace...'

            script {

                try {

                    bat "docker logout"

                } catch(Exception e) {

                    echo "Docker logout skipped"
                }

                cleanWs()
            }
        }
    }
}